### ISSUE TITLE
TCP echo server is good, but where is Unix Socket echo server?

### ISSUE THREAD

**Issue by Globik** [litesync/libuv_message_framing#1]
I'd like to test it with named pipes, but can't to find any working example with named unix sockets server and client.

**Comment by kroggen** [comment]
Hi!

We can use [pipe-echo-server](https://github.com/libuv/libuv/tree/v1.x/docs/code/pipe-echo-server)

But you are right, we need more examples. I will add them.

**Comment by kroggen** [comment]
Done.

We can compile the examples for pipes/unix domain sockets like this:

```
gcc echo-server.c -o echo-server -luv -DUSE_PIPE_EXAMPLE
gcc example2.c -o example2 -luv -DUSE_PIPE_EXAMPLE
```

**Comment by Globik** [comment]
Thank you.
